{% set name = "CADET" %}
{% set version = "5.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/modsim/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 041c0a0c7148041227e4e2fdd942046bf3aa93c9545d6a33f1c3d535de19fc6e

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - git
    - cmake
    - make  # [unix]
  host:
    - superlu  # [not win]
    - suitesparse
    - tbb-devel
    - hdf5
    - eigen
    - libblas
    - libcblas
    - liblapack
  run:
    - superlu  # [not win]
    - suitesparse
    - tbb-devel
    - hdf5

about:
  home: https://github.com/modsim/cadet
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE.txt
  summary: 'An open platform for integrated process modelling and simulation'
  description: The CADET software is a fast and accurate solver for a comprehensive model family. Typical applications include (but are not limited to) chromatography, filtration, crystallization, and fermentation. CADET can handle arbitrary sequences and networks of unit operations, including reactors, tanks, tubes, pumps,
    valves, detectors, etc. The resulting models are solved with state-of-the-art mathematical algorithms and scientific computing techniques.
  doc_url: https://cadet.github.io/
  dev_url: https://github.com/modsim/cadet

extra:
  recipe-maintainers:
    - schmoelder
    - jbreue16
    - ronald-jaepel
