conda_forge_output_validation: true
os_version:
  linux_64: cos7
build_platform:
  osx_arm64: osx_64
test: native_and_emulated
github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  pkg_format: 2
